author: Tuist
module: shell
github_url: https://github.com/tuist/shell
copyright: 'Copyright © from 2018 Pedro Piñera Buendía. All rights reserved.'
readme: ABOUT.md
sdk: macosx
min_acl: internal
xcodebuild_arguments:
  - -project
  - shell.xcodeproj
  - -scheme
  - shell-Package
skip_undocumented: true
